version: '3.8'

services:
  user-service:
    build:
      context: ./user-service
    ports:
      - 5001:5001
    volumes:
      - ./user-service:/app

  product-service:
    build:
      context: ./product-service
    ports:
      - 5002:5002
    volumes:
      - ./product-service:/app

  order-service:
    build:
      context: ./order-service
    ports:
      - 5003:5003
    volumes:
      - ./order-service:/app

  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - 5000:5000
    depends_on:
      - user-service
      - product-service
      - order-service

