version: '3.8'
services:
  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - '4001:4001'

  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - '4002:4002'

  cart-service:
    build: ./cart-service
    container_name: cart-service
    ports:
      - '4003:4003'

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - '4000:4000'
    depends_on:
      - auth-service
      - product-service
      - cart-service
