global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:4001']

  - job_name: 'product-service'
    static_configs:
      - targets: ['product-service:4002']

  - job_name: 'cart-service'
    static_configs:
      - targets: ['cart-service:4003']
   
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
